### ISSUE TITLE
STIG-Manager on port 54000 renders an error

### ISSUE THREAD

**Issue by gregglowrimore** [NUWCDIVNPT/stigman-orchestration#11]
@cd-rite We got the STIG-Manager-linuxstatic binary to run the other day. Now hitting the http://stigman:54000/ page renders an error stating it's an insecure protocol and STIG-Manager REQUIRES an https / secure page. So re-adding the CERT and KEY files to stig-manager.sh (to enable TLS connections?) now crashes stig-manager-linuxstatic like before. Sort of a catch-22.

How is STIG-Manager to be configured for https TLS connections?

**Comment by cd-rite** [comment]
Hi @gregglowrimore You definitely don't want to set any "STIGMAN_DB_TLS_XXXXXX" variables, they are strictly for establishing TLS from the API to the DB, which is not the issue you are having. 

STIGMan itself does not support https requests, it expects to be forwarded those requests from your nginx proxy. Do you have a proxy configured for https? You mentioned a proxy in your other issue so I'm assuming so. 

That message might be from your browser hitting the proxy and requiring a secure connection.  Your browser needs to know about the CAs you configured nginx with. There is some info about this in the README for this repo: https://github.com/NUWCDIVNPT/stigman-orchestration?tab=readme-ov-file#requirements-for-running-the-example


From what you are saying, the API is up and running according to the logs, you just can't hit it with the web browser? Maybe take the proxy out of the picture for now, and just go to localhost:54000 in the browser?

**Comment by gregglowrimore** [comment]
I got it all working! It was a combination of keycloak.conf, stig-manager env variables and nginx.conf changes, coupled with an update to the redirect URI once Keycloak logs one in.

Thanks a BUNCH for your helpful insights and direct. Much appreciated. Now to bring all my hand-jams back in to our IaC (Terraform+Ansible)

**Comment by cd-rite** [comment]
Awesome! Glad to hear that!
